"""
Placeholder alembic script template.
Actual migration scripts are generated by: alembic revision --autogenerate -m "description"
"""
from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
